# $schema: http://json.schemastore.org/github-workflow.json
name: pull-request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  verify-github-workflows:
    uses: harmelodic/workflows/.github/workflows/verify-github-workflows.yaml@0d1dba555e14649f81c4022aaae4685b2ee916ba

  verify-javascript-project:
    uses: harmelodic/workflows/.github/workflows/verify-javascript-project.yaml@0d1dba555e14649f81c4022aaae4685b2ee916ba
